version: '3'

services: 
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports: 
      - ${PORT}:${PORT}
    links: 
      - postgres:postgres
    depends_on: 
      - postgres
    restart: unless-stopped
  
  postgres:
    image: postgres:13.2
    restart: always
    ports: 
      - 5432:5432
    env_file: 
      - .env
    environment: 
      - ${POSTGRES_USER}:${POSTGRES_USER}
      - ${POSTGRES_PASSWORD}:${POSTGRES_PASSWORD}
      - ${POSTGRES_DB}:${POSTGRES_DB}
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    